### ISSUE TITLE
Purge state on logout?

### ISSUE THREAD

**Issue by egoldschmidt** [iteratehq/react-native-iterate#36]
When users log out of our app, I clear fields like email address by calling `identify` with `null` fields. But upon login it seems that new user data is being associated with the _old_ survey records in Integrate's backend. Example:

1. User 1 login => `.identify({email: user1@gmail.com})`
2. User 1 submit `survey1`
3. User 1 logout => `.identify({email: null})`
4. User 2 login => `.identify({email: user2@gmail.com})`
5. User 2 submit `survey2`

The Integrate backend now shows `survey1` and `survey2` both associated with `user2`. Interestingly this seems to also happen even through full app delete/reset?

There is a fair bit of phone device reuse in our user population, so this use case is important to cover to avoid misattributing survey data.

**Comment by msingleton** [comment]
Ah yea that's a great point. That's caused because we store an API key for the user, which determines who that user is, it's being persisted using secure storage (e.g. keychain on iOS) which survives an app reset. 

We'll add a "clear" method that you can call on logout that will remove the API key as well as all other data (e.g. data from .Identify). Shouldn't take long.

**Comment by msingleton** [comment]
@egoldschmidt this is live now with version 1.2.0

**Comment by egoldschmidt** [comment]
Aw shucks, thanks!
